version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: employee-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_management_system

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    networks:
      - employee-network


  backend:
    image: employee-backend:1.0

    container_name: employee-backend

    depends_on:
      - mysql

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_management_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - employee-network


  frontend:
    image: employee-frontend:1.0

    container_name: employee-frontend

    depends_on:
      - backend

    ports:
      - "3000:80"

    networks:
      - employee-network


volumes:
  mysql-data:

networks:
  employee-network: